# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: zeronus.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'zeronus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rzeronus.proto\x12\x07zeronus\"\x0f\n\rHealthRequest\"0\n\x0bHealthReply\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\r\n\x0bListRequest\"+\n\nPluginInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\"2\n\nPluginList\x12$\n\x07plugins\x18\x01 \x03(\x0b\x32\x13.zeronus.PluginInfo\")\n\x0bServiceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"5\n\x0bServiceList\x12&\n\x08services\x18\x01 \x03(\x0b\x32\x14.zeronus.ServiceInfo\"1\n\x0b\x45mitRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0cpayload_json\x18\x02 \x01(\t\"*\n\tEmitReply\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x11\n\tlisteners\x18\x02 \x01(\x05\x32\xee\x01\n\x07Zeronus\x12\x36\n\x06Health\x12\x16.zeronus.HealthRequest\x1a\x14.zeronus.HealthReply\x12\x38\n\x0bListPlugins\x12\x14.zeronus.ListRequest\x1a\x13.zeronus.PluginList\x12:\n\x0cListServices\x12\x14.zeronus.ListRequest\x1a\x14.zeronus.ServiceList\x12\x35\n\tEmitEvent\x12\x14.zeronus.EmitRequest\x1a\x12.zeronus.EmitReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'zeronus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=26
  _globals['_HEALTHREQUEST']._serialized_end=41
  _globals['_HEALTHREPLY']._serialized_start=43
  _globals['_HEALTHREPLY']._serialized_end=91
  _globals['_LISTREQUEST']._serialized_start=93
  _globals['_LISTREQUEST']._serialized_end=106
  _globals['_PLUGININFO']._serialized_start=108
  _globals['_PLUGININFO']._serialized_end=151
  _globals['_PLUGINLIST']._serialized_start=153
  _globals['_PLUGINLIST']._serialized_end=203
  _globals['_SERVICEINFO']._serialized_start=205
  _globals['_SERVICEINFO']._serialized_end=246
  _globals['_SERVICELIST']._serialized_start=248
  _globals['_SERVICELIST']._serialized_end=301
  _globals['_EMITREQUEST']._serialized_start=303
  _globals['_EMITREQUEST']._serialized_end=352
  _globals['_EMITREPLY']._serialized_start=354
  _globals['_EMITREPLY']._serialized_end=396
  _globals['_ZERONUS']._serialized_start=399
  _globals['_ZERONUS']._serialized_end=637
# @@protoc_insertion_point(module_scope)
