# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import zeronus_pb2 as zeronus__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in zeronus_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ZeronusStub:
    """Zeronus gRPC 对外服务：暴露框架内省与事件发布能力
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/zeronus.Zeronus/Health',
                request_serializer=zeronus__pb2.HealthRequest.SerializeToString,
                response_deserializer=zeronus__pb2.HealthReply.FromString,
                _registered_method=True)
        self.ListPlugins = channel.unary_unary(
                '/zeronus.Zeronus/ListPlugins',
                request_serializer=zeronus__pb2.ListRequest.SerializeToString,
                response_deserializer=zeronus__pb2.PluginList.FromString,
                _registered_method=True)
        self.ListServices = channel.unary_unary(
                '/zeronus.Zeronus/ListServices',
                request_serializer=zeronus__pb2.ListRequest.SerializeToString,
                response_deserializer=zeronus__pb2.ServiceList.FromString,
                _registered_method=True)
        self.EmitEvent = channel.unary_unary(
                '/zeronus.Zeronus/EmitEvent',
                request_serializer=zeronus__pb2.EmitRequest.SerializeToString,
                response_deserializer=zeronus__pb2.EmitReply.FromString,
                _registered_method=True)


class ZeronusServicer:
    """Zeronus gRPC 对外服务：暴露框架内省与事件发布能力
    """

    def Health(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlugins(self, request, context):
        """已加载插件列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """已注册服务列表
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmitEvent(self, request, context):
        """发布一个事件到内核事件总线
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ZeronusServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=zeronus__pb2.HealthRequest.FromString,
                    response_serializer=zeronus__pb2.HealthReply.SerializeToString,
            ),
            'ListPlugins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlugins,
                    request_deserializer=zeronus__pb2.ListRequest.FromString,
                    response_serializer=zeronus__pb2.PluginList.SerializeToString,
            ),
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=zeronus__pb2.ListRequest.FromString,
                    response_serializer=zeronus__pb2.ServiceList.SerializeToString,
            ),
            'EmitEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.EmitEvent,
                    request_deserializer=zeronus__pb2.EmitRequest.FromString,
                    response_serializer=zeronus__pb2.EmitReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeronus.Zeronus', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zeronus.Zeronus', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Zeronus:
    """Zeronus gRPC 对外服务：暴露框架内省与事件发布能力
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeronus.Zeronus/Health',
            zeronus__pb2.HealthRequest.SerializeToString,
            zeronus__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlugins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeronus.Zeronus/ListPlugins',
            zeronus__pb2.ListRequest.SerializeToString,
            zeronus__pb2.PluginList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeronus.Zeronus/ListServices',
            zeronus__pb2.ListRequest.SerializeToString,
            zeronus__pb2.ServiceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmitEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zeronus.Zeronus/EmitEvent',
            zeronus__pb2.EmitRequest.SerializeToString,
            zeronus__pb2.EmitReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
